### ISSUE TITLE
[Feature request] Use firebase for authentication

### ISSUE THREAD

**Issue by arthuro555** [damian-pastorini/reldens#115]
Proposition : use Firebase for authentication. It is easy to integrate, always free, trustworthy and secure (as it is made by Google using the same systems as Google.) It would be useful/easier for you and guarantee security and easiness for every user.

**Comment by damian-pastorini** [comment]
Thanks for the suggestion! I'm about to push beta.12 with a lot of changes, and the next one will include all the registration improvements.

**Comment by damian-pastorini** [comment]
![image](https://user-images.githubusercontent.com/1211779/87861520-5b4f3500-c947-11ea-919e-d12cb798a2ee.png)

Firebase started to look good 👍

**Comment by damian-pastorini** [comment]
Included in https://github.com/damian-pastorini/reldens/pull/119
