### ISSUE TITLE
is mobile devices supported?

### ISSUE THREAD

**Issue by jrichardsz** [damian-pastorini/reldens#164]
Hi. Your project is amazing!

I was researching about this retro games in android. I found browser-quest and works in android browsers:

- https://github.com/mozilla/BrowserQuest

Can your game run in a mobile browser with success touch and responsive dimensions ? 

Thanks for your time

**Comment by damian-pastorini** [comment]
Hi @jrichardsz , yes it does, you can check the demo in your phone.
