### ISSUE TITLE
Docker-compose quickstart

### ISSUE THREAD

**Issue by zewa666** [damian-pastorini/reldens#190]
Hey there, very cool project. I stumbled over it a couple of times reading articles and also talking to you over at the Phaser3 discord channel. After trying out your game I wanted to take a quick look at it locally but found it involves quite a few steps to get started, namely having a MySQL server available.

Now a quick idea I had was to have a docker-compose file coming with your repository so that anyone wanting to give it a try merely would need to run:

```
cd LOCAL-GIT-CLONE
docker-compose up
```

and it would setup a default MySQL (+ your demo dump) and a node container starting your game with a nodemon filewatcher or the likes to run whats behind `npm start`

**Comment by damian-pastorini** [comment]
Thanks for the recoomendation @zewa666 , I just put it in the road map: https://github.com/damian-pastorini/reldens/projects/2
